/**
 * AI Service Layer
 * Provides intelligent features including task prioritization, pattern learning, and smart suggestions
 */

import { calculateTaskPriority, TaskPriority, UserContext } from './task-prioritizer'
import { getUserPatterns, UserPattern, predictCompletionTime } from './patterns'

// Re-export for convenience
export * from './task-prioritizer'
export * from './patterns'
export * from './embeddings'

/**
 * AI Recommendation
 * Represents a suggestion generated by the AI system
 */
export interface AIRecommendation {
  id: string
  type: 'priority' | 'schedule' | 'breakdown' | 'automation' | 'batch' | 'delegate' | 'energy'
  title: string
  description: string
  confidence: number
  payload: Record<string, unknown>
  createdAt: number
  aiReason?: string
  action: {
    label: string
    type: 'create_task' | 'update_task' | 'navigate'
    payload?: Record<string, unknown>
  }
}

/**
 * AI Context
 * The context needed for AI analysis
 */
export interface AIContext {
  tasks: import('@/types').Task[]
  user: UserContext
  history: import('@/types').TaskLog[]
}

/**
 * Calculate priority scores for multiple tasks
 * Uses ML model to analyze and score each task
 */
export async function prioritizeTasks(tasks: import('@/types').Task[], context: UserContext): Promise<Map<string, TaskPriority>> {
  const scores = new Map<string, TaskPriority>()

  for (const task of tasks) {
    const priority = await calculateTaskPriority(task, context)
    scores.set(task.id, priority)
  }

  return scores
}

/**
 * Get AI-generated recommendations
 * Analyzes user's tasks and patterns to generate actionable suggestions
 */
export async function getRecommendations(context: AIContext): Promise<AIRecommendation[]> {
  const patterns = await getUserPatterns()
  const recommendations: AIRecommendation[] = []

  // Detect task clustering opportunities
  const similarTasks = findBatchableTaskIds(context.tasks)
  if (similarTasks.length > 0) {
    recommendations.push({
      id: `batch-${Date.now()}`,
      type: 'batch',
      title: `Group ${similarTasks.length} similar tasks`,
      description: 'These tasks can be batched together for efficiency',
      confidence: 0.8,
      payload: { taskIds: similarTasks },
      createdAt: Date.now(),
      action: {
        label: 'View Tasks',
        type: 'navigate',
        payload: { taskIds: similarTasks }
      },
    })
  }

  // Detect scheduling opportunities
  const optimalTimes = patterns.energyPatterns?.optimalTimes || []
  if (optimalTimes.length > 0) {
    const highPriorityTasks = context.tasks.filter(t => !t.completed && t.priority === 'high')
    if (highPriorityTasks.length > 0) {
      recommendations.push({
        id: `schedule-${Date.now()}`,
        type: 'schedule',
        title: 'Schedule high-priority tasks at optimal times',
        description: `Your most productive times are: ${optimalTimes.join(', ')}`,
        confidence: 0.9,
        payload: { taskIds: highPriorityTasks.map(t => t.id), times: optimalTimes },
        createdAt: Date.now(),
        action: {
          label: 'View Tasks',
          type: 'navigate',
          payload: { taskIds: highPriorityTasks.map(t => t.id), times: optimalTimes }
        },
      })
    }
  }

  // Detect automation opportunities
  const recurringTasks = context.tasks.filter(t => t.recurring && !t.completed)
  if (recurringTasks.length >= 3) {
    recommendations.push({
      id: `automation-${Date.now()}`,
      type: 'automation',
      title: 'Automate recurring tasks',
      description: `${recurringTasks.length} recurring tasks could be automated with a workflow`,
      confidence: 0.85,
      payload: { taskIds: recurringTasks.map(t => t.id) },
      createdAt: Date.now(),
      action: {
        label: 'Create Workflow',
        type: 'navigate',
        payload: { taskIds: recurringTasks.map(t => t.id) }
      },
    })
  }

  return recommendations
}

/**
 * Find tasks of comparable size that could be batched together.
 * NOTE: distinct from the semantic `findSimilarTasks` in ./embeddings —
 * this one buckets by estimated duration, not by text meaning.
 */
function findBatchableTaskIds(tasks: import('@/types').Task[]): string[] {
  if (tasks.length < 2) return []

  const incomplete = tasks.filter(t => !t.completed)
  const byEstimate = new Map<number, string[]>()

  for (const task of incomplete) {
    const estimate = task.estimate || 30
    const key = Math.floor(estimate / 30) * 30 // Round to nearest 30 min
    if (!byEstimate.has(key)) {
      byEstimate.set(key, [])
    }
    byEstimate.get(key)!.push(task.id)
  }

  // Return task IDs that have at least 2 similar tasks
  const similar: string[] = []
  for (const taskIds of byEstimate.values()) {
    if (taskIds.length >= 2) {
      similar.push(...taskIds)
    }
  }

  return similar.slice(0, 10) // Cap at 10 tasks
}

/**
 * Get the main AI service instance.
 *
 * `predictCompletionTime` is re-exported from `./patterns` (the
 * `export *` above shadows any local definition), so this object
 * exposes the richer `CompletionTimePrediction` version that uses
 * category averages, calibrated estimates, and confidence metadata.
 */
export const aiService = {
  prioritizeTasks,
  getRecommendations,
  predictCompletionTime,
}